import { lazy } from 'react';

export {
  backupCodesCount,
  changePassword as changeIssuerPassword,
  connectedApps,
  deleteAccount,
  favorites,
  generateBackupCodes,
  issuerAccount,
  issuerGuestAccount,
  linkProvider,
  linkedAccounts,
  menuFavorites,
  passkeyCreationOptions,
  passkeys,
  placesKey,
  preferTfa,
  profile,
  providerStatus,
  registerPasskey,
  removePasskey,
  removeTfaMethod,
  renamePasskey,
  requestEmailChange,
  revokeSession,
  revokeSessions,
  saveFavorites,
  savePreferences,
  sendPhoneCode,
  sendTfaSms,
  sessions,
  setTfa,
  stepUp,
  tfaEnroll,
  tfaMethods,
  unlinkProvider,
  updateAddress,
  updateDetails,
  verifyEmailChange,
  verifyPhone,
  verifyTfaApp,
  verifyTfaSms,
} from './api/account';
export {
  cancelRequest,
  changeEmail,
  changeName,
  changePassword,
  leaveOrganization,
  myRequests,
  patchProfile,
  removeAccount,
  resendVerification,
  serviceAccounts,
  setPrimaryOrganization,
  verifyMail,
} from './api/profile';
export { PROFILE_ROUTE_SECTIONS, accountShape, sectionsFor } from './sections';
export { sidebar } from './sidebar';

export const ProfilePage = lazy(() => import('./components/ProfilePage'));
