import PropTypes from 'prop-types';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';

import { VLAN_FORM, vlanAutoName, vlanProblem } from '../utils/networkingManagement';

import ToolFormDialog from './ToolFormDialog';

const named = (form, vlans) => {
  const auto = vlanAutoName(form.link, form.vid);
  const taken = vlans.some(vlan => vlan.link === auto);
  return { ...form, name: auto && !taken ? auto : '' };
};

/**
 * The create dialog of a VLAN, hyperweaver-ui's: the id, the physical
 * link, the name suggested by dladm's formula (`vlanAutoName`) and
 * cleared where a held VLAN takes it, the force and temporary flags.
 * The form's problem draws over the fields and holds the send; the body
 * is `vlanBody`.
 */
const VlanCreateModal = ({ links, vlans, busy, onClose, onSubmit }) => {
  const { t } = useTranslation();
  const [form, setForm] = useState(VLAN_FORM);
  const [tried, setTried] = useState(false);
  const problem = vlanProblem(form);

  const change = (field, value) =>
    setForm(current => {
      const next = { ...current, [field]: value };
      return field === 'vid' || field === 'link' ? named(next, vlans) : next;
    });

  const submit = () => {
    setTried(true);
    if (!problem) {
      onSubmit(form);
    }
  };

  return (
    <ToolFormDialog
      dialog="vlan-create"
      title={t('host.vlanCreateModal.createVlan')}
      submitKey="host.vlanCreateModal.createVlan"
      problemKey={tried ? problem : ''}
      busy={busy}
      onClose={onClose}
      onSubmit={submit}
    >
      <div className="row g-3">
        <div className="col">
          <div className="mb-3">
            <label className="form-label" htmlFor="vlan-create-vid">
              {t('host.vlanCreateModal.vlanIdLabel')} *
            </label>
            <input
              id="vlan-create-vid"
              className="form-control"
              type="number"
              min="1"
              max="4094"
              placeholder={t('host.vlanCreateModal.vlanIdPlaceholder')}
              value={form.vid}
              onChange={event => change('vid', event.target.value)}
              disabled={busy}
              required
            />
            <p className="form-text text-muted">{t('host.vlanCreateModal.validRange')}</p>
          </div>
        </div>
        <div className="col">
          <div className="mb-3">
            <label className="form-label" htmlFor="vlan-create-link">
              {t('host.vlanCreateModal.physicalLinkLabel')} *
            </label>
            <select
              id="vlan-create-link"
              className="form-select"
              value={form.link}
              onChange={event => change('link', event.target.value)}
              disabled={busy}
              required
            >
              <option value="">{t('host.vlanCreateModal.selectPhysicalInterface')}</option>
              {links.map(row => (
                <option key={row.link} value={row.link}>
                  {row.link} ({row.state || 'unknown'}, {row.speed || 'unknown'})
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>
      <div className="mb-3">
        <label className="form-label" htmlFor="vlan-create-name">
          {t('host.vlanCreateModal.vlanNameOptional')}
        </label>
        <input
          id="vlan-create-name"
          className="form-control"
          type="text"
          placeholder={t('host.vlanCreateModal.autoGeneratedPlaceholder')}
          value={form.name}
          onChange={event => change('name', event.target.value)}
          disabled={busy}
        />
        <p className="form-text text-muted">{t('host.vlanCreateModal.autoGeneratedHelp')}</p>
      </div>
      <div className="mb-3">
        <div className="form-check">
          <input
            id="vlan-create-force"
            className="form-check-input"
            type="checkbox"
            checked={form.force}
            onChange={event => change('force', event.target.checked)}
            disabled={busy}
          />
          <label className="form-check-label" htmlFor="vlan-create-force">
            {t('host.vlanCreateModal.forceCreation')}
          </label>
        </div>
        <p className="form-text text-muted small">{t('host.vlanCreateModal.forceCreationHelp')}</p>
      </div>
      <div className="mb-3">
        <div className="form-check">
          <input
            id="vlan-create-temporary"
            className="form-check-input"
            type="checkbox"
            checked={form.temporary}
            onChange={event => change('temporary', event.target.checked)}
            disabled={busy}
          />
          <label className="form-check-label" htmlFor="vlan-create-temporary">
            {t('host.vlanCreateModal.temporaryLabel')}
          </label>
        </div>
      </div>
    </ToolFormDialog>
  );
};

VlanCreateModal.propTypes = {
  links: PropTypes.array.isRequired,
  vlans: PropTypes.array.isRequired,
  busy: PropTypes.bool.isRequired,
  onClose: PropTypes.func.isRequired,
  onSubmit: PropTypes.func.isRequired,
};

export default VlanCreateModal;
